spring.application.name=event_zone
# env.properties file import
spring.config.import=file:env.properties
# Web Server configuration
server.port=${PORT}
# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
# JWT Secret
jwt.secret=${JWT_SECRET}